### ISSUE TITLE
修改后的界面保存报错

### ISSUE THREAD

**Issue by jianghuanlong** [yangxu998/Junyi#7]
所有界面，右侧窗口有变动时，直接点击页签上的关闭按钮，出现提示信息“有未保存数据，按【是】保存数据并关闭，按【否】不保存并关闭，按【取消】继续编辑”。按【是】后，窗口关闭，但数据没有保存；按【否】和按【取消】，工具直接关闭，后台报错

**Comment by yangxu998** [comment]
ok
